// Points action types
export const FETCH_POINTS_REQUEST = "FETCH_POINTS_REQUEST";
export const FETCH_POINTS_SUCCESS = "FETCH_POINTS_SUCCESS";
export const FETCH_POINTS_FAILURE = "FETCH_POINTS_FAILURE";

export const ADD_POINT_REQUEST = "ADD_POINT_REQUEST";
export const ADD_POINT_SUCCESS = "ADD_POINT_SUCCESS";
export const ADD_POINT_FAILURE = "ADD_POINT_FAILURE";

export const UPDATE_POINT_REQUEST = "UPDATE_POINT_REQUEST";
export const UPDATE_POINT_SUCCESS = "UPDATE_POINT_SUCCESS";
export const UPDATE_POINT_FAILURE = "UPDATE_POINT_FAILURE";

export const DELETE_POINT_REQUEST = "DELETE_POINT_REQUEST";
export const DELETE_POINT_SUCCESS = "DELETE_POINT_SUCCESS";
export const DELETE_POINT_FAILURE = "DELETE_POINT_FAILURE";

// Pictures action types
export const FETCH_PICTURES_REQUEST = "FETCH_PICTURES_REQUEST";
export const FETCH_PICTURES_SUCCESS = "FETCH_PICTURES_SUCCESS";
export const FETCH_PICTURES_FAILURE = "FETCH_PICTURES_FAILURE";

export const UPLOAD_PICTURE_REQUEST = "UPLOAD_PICTURE_REQUEST";
export const UPLOAD_PICTURE_SUCCESS = "UPLOAD_PICTURE_SUCCESS";
export const UPLOAD_PICTURE_FAILURE = "UPLOAD_PICTURE_FAILURE";

export const DELETE_PICTURE_REQUEST = "DELETE_PICTURE_REQUEST";
export const DELETE_PICTURE_SUCCESS = "DELETE_PICTURE_SUCCESS";
export const DELETE_PICTURE_FAILURE = "DELETE_PICTURE_FAILURE";

// Videos action types
export const FETCH_VIDEOS_REQUEST = "FETCH_VIDEOS_REQUEST";
export const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS";
export const FETCH_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE";

export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_FAILURE = "UPLOAD_VIDEO_FAILURE";

export const DELETE_VIDEO_REQUEST = "DELETE_VIDEO_REQUEST";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_FAILURE = "DELETE_VIDEO_FAILURE";

// Add these to your existing types
export const FETCH_HAS_PICTURES_REQUEST = "FETCH_HAS_PICTURES_REQUEST";
export const FETCH_HAS_PICTURES_SUCCESS = "FETCH_HAS_PICTURES_SUCCESS";
export const FETCH_HAS_PICTURES_FAILURE = "FETCH_HAS_PICTURES_FAILURE";

export const BULK_FETCH_HAS_PICTURES_REQUEST =
  "BULK_FETCH_HAS_PICTURES_REQUEST";
export const BULK_FETCH_HAS_PICTURES_SUCCESS =
  "BULK_FETCH_HAS_PICTURES_SUCCESS";
export const BULK_FETCH_HAS_PICTURES_FAILURE =
  "BULK_FETCH_HAS_PICTURES_FAILURE";

export const FETCH_HAS_VIDEOS_REQUEST = "FETCH_HAS_VIDEOS_REQUEST";
export const FETCH_HAS_VIDEOS_SUCCESS = "FETCH_HAS_VIDEOS_SUCCESS";
export const FETCH_HAS_VIDEOS_FAILURE = "FETCH_HAS_VIDEOS_FAILURE";

export const BULK_FETCH_HAS_VIDEOS_REQUEST = "BULK_FETCH_HAS_VIDEOS_REQUEST";
export const BULK_FETCH_HAS_VIDEOS_SUCCESS = "BULK_FETCH_HAS_VIDEOS_SUCCESS";
export const BULK_FETCH_HAS_VIDEOS_FAILURE = "BULK_FETCH_HAS_VIDEOS_FAILURE";
// Add these to your existing types.js file

// Tags action types
export const FETCH_TAGS_REQUEST = "FETCH_TAGS_REQUEST";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAILURE = "FETCH_TAGS_FAILURE";

export const FETCH_TAG_REQUEST = "FETCH_TAG_REQUEST";
export const FETCH_TAG_SUCCESS = "FETCH_TAG_SUCCESS";
export const FETCH_TAG_FAILURE = "FETCH_TAG_FAILURE";

export const CREATE_TAG_REQUEST = "CREATE_TAG_REQUEST";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_FAILURE = "CREATE_TAG_FAILURE";

export const UPDATE_TAG_REQUEST = "UPDATE_TAG_REQUEST";
export const UPDATE_TAG_SUCCESS = "UPDATE_TAG_SUCCESS";
export const UPDATE_TAG_FAILURE = "UPDATE_TAG_FAILURE";

export const DELETE_TAG_REQUEST = "DELETE_TAG_REQUEST";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
export const DELETE_TAG_FAILURE = "DELETE_TAG_FAILURE";

export const FETCH_TAGS_BY_CATEGORY_REQUEST = "FETCH_TAGS_BY_CATEGORY_REQUEST";
export const FETCH_TAGS_BY_CATEGORY_SUCCESS = "FETCH_TAGS_BY_CATEGORY_SUCCESS";

// Picture Tags action types
export const FETCH_PICTURE_TAGS_REQUEST = "FETCH_PICTURE_TAGS_REQUEST";
export const FETCH_PICTURE_TAGS_SUCCESS = "FETCH_PICTURE_TAGS_SUCCESS";
export const FETCH_PICTURE_TAGS_FAILURE = "FETCH_PICTURE_TAGS_FAILURE";

export const FETCH_TAGS_FOR_PICTURE_REQUEST = "FETCH_TAGS_FOR_PICTURE_REQUEST";
export const FETCH_TAGS_FOR_PICTURE_SUCCESS = "FETCH_TAGS_FOR_PICTURE_SUCCESS";
export const FETCH_TAGS_FOR_PICTURE_FAILURE = "FETCH_TAGS_FOR_PICTURE_FAILURE";

export const FETCH_PICTURES_FOR_TAG_REQUEST = "FETCH_PICTURES_FOR_TAG_REQUEST";
export const FETCH_PICTURES_FOR_TAG_SUCCESS = "FETCH_PICTURES_FOR_TAG_SUCCESS";
export const FETCH_PICTURES_FOR_TAG_FAILURE = "FETCH_PICTURES_FOR_TAG_FAILURE";

export const ADD_TAG_TO_PICTURE_REQUEST = "ADD_TAG_TO_PICTURE_REQUEST";
export const ADD_TAG_TO_PICTURE_SUCCESS = "ADD_TAG_TO_PICTURE_SUCCESS";
export const ADD_TAG_TO_PICTURE_FAILURE = "ADD_TAG_TO_PICTURE_FAILURE";

export const REMOVE_TAG_FROM_PICTURE_REQUEST = "REMOVE_TAG_FROM_PICTURE_REQUEST";
export const REMOVE_TAG_FROM_PICTURE_SUCCESS = "REMOVE_TAG_FROM_PICTURE_SUCCESS";
export const REMOVE_TAG_FROM_PICTURE_FAILURE = "REMOVE_TAG_FROM_PICTURE_FAILURE";

export const SEARCH_PICTURES_BY_TAGS_REQUEST = "SEARCH_PICTURES_BY_TAGS_REQUEST";
export const SEARCH_PICTURES_BY_TAGS_SUCCESS = "SEARCH_PICTURES_BY_TAGS_SUCCESS";
export const SEARCH_PICTURES_BY_TAGS_FAILURE = "SEARCH_PICTURES_BY_TAGS_FAILURE";
export const FETCH_TAGS_BY_CATEGORY_FAILURE = "FETCH_TAGS_BY_CATEGORY_FAILURE";

// Picture Album action types
export const FETCH_PICTURE_ALBUM_REQUEST = "FETCH_PICTURE_ALBUM_REQUEST";
export const FETCH_PICTURE_ALBUM_SUCCESS = "FETCH_PICTURE_ALBUM_SUCCESS";
export const FETCH_PICTURE_ALBUM_FAILURE = "FETCH_PICTURE_ALBUM_FAILURE";

export const FILTER_PICTURE_ALBUM_BY_TAGS = "FILTER_PICTURE_ALBUM_BY_TAGS";
export const RESET_PICTURE_ALBUM_FILTERS = "RESET_PICTURE_ALBUM_FILTERS";

export const SET_CURRENT_ALBUM_IMAGE = "SET_CURRENT_ALBUM_IMAGE";
export const SET_ALBUM_ZOOM_LEVEL = "SET_ALBUM_ZOOM_LEVEL";
export const SET_IMAGE_INDIVIDUAL_ZOOM = "SET_IMAGE_INDIVIDUAL_ZOOM";
export const TOGGLE_ALBUM_PHOTO_VIEWER = "TOGGLE_ALBUM_PHOTO_VIEWER";
export const SET_YEAR_FILTER = "SET_YEAR_FILTER";